### ISSUE TITLE
Different approaches on Entrypoint layer tests

### ISSUE THREAD

**Issue by paulohenriquepm** [GeekHunter-Brasil/hello-world#10]
On the back-end, we have decided to do integration tests on the Entrypoint Layer (e.g. controllers, mutations, etc...), but the way that we are doing is a bit redundant.

We decided to check if a manager were called correctly (to do so, we need to mock, so we aren`t the test is not anymore a fully integration one), but in some cases, this can be very helpful, like when we are handling a legacy code, in the other hand, when testing Mutations, this check is redundant due to graphql.

I am willing to use both ways and adapt depending on what we are testing.

What do you think?

**Comment by Thrashattack** [comment]
```
Cypress was covering the integration front over the tests for the Legacy code. 
In this case i belive we can use both, mocks and integration for tests that covers the legacy code.

```

**Comment by renanrcp** [comment]
We don't use cypress today, I think with legacy code we can still mock in some inner context, but always use integration tests in outside

**Comment by joaophellip** [comment]
Nice issue and cudos for bringing that up. I think it a point worth of discussion with a lot subtleties and I'd try to address some.

I firmely believe we should adopt a well-defined set of test strategies that apply to _all entrypoint modules_ and eventually cope with particularities as they appear. And I'll try to argue why I think this is better.

The first strategy is more general and I think it should be part of a separate stylguide for tests. It is the well-known [testing pyramid](https://martinfowler.com/articles/practical-test-pyramid.html), to which I advocate we pay closer attention. This principle entails that we write fewer integration tests than unit ones. By following it, we can safely assume the manager has a set of unit tests that cover the inner business logic. By transitivity that applies to other inner layers as well.

Another strategy I'm in favor of adoption is the [whitebox testing](https://en.wikipedia.org/wiki/White-box_testing) for integration. Our styleguide implicitly adopts that but it maybe worth making it explict. That means we not only assert responses and interactions with external code (databases, apis) but we also assert how our controller is interacting with the manager. I know this kind of approaching ain't a consensus and I'd like to hear your thoughts on that. To me, it gives us higher confidence that our code is working as expected: image a scenario where we refactor a controller and introduce a bug where new and unexpected arguments are passed to a manager; bug may be shadowed if we don't explicitly assert this inner integration. And even if it surfaces in a database assertion, it is much harder to track it down only by doing that.

Taking these two strategies into account, there's a way of doing that in RSpec by using [and_call_original](https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation): it is like a spy in a real object. That makes easier to write/review/undestand a spec without the need to have two separate scenarios (and additional state control) to do it. But note I'm not saying integration tests are easy to write/maintain; in fact I find them more complicated than unit ones. Good news is: we have fewer :)

Last but not least, let's assume controllers are responsible for parsing, and to some extend, for transforming the input params into a different object that is passed along to the manager. I.e. it is nothing more than a function _f:A->B_ and therefore we should also make sure we assert _f_, i.e. that for _a in A_, the output _b e B_ is what we hope it is. 

Putting it all together, we could have: 

```
    context 'when request params is valid' do
      let(:hiring_params) do
        { hiring: {
          candidate_id: candidate.id,
          job_id: job.id,
          candidate_start_date: '2022-02-11 15:54:29 -0300',
          candidate_salary: 5000,
          origin: Hiring.origin.package,
          contract_type: Hiring.contract_type.clt
        } }
      end
      let(:manager_params) do
        manager_params = ActionController::Parameters.new(hiring_params)
          .require(:hiring)
          .permit(:job_id, :candidate_start_date, :candidate_salary, :origin, :contract_type)
        manager_params[:job_id] = job.id.to_s
        manager_params[:bid_id] = 1
        manager_params[:candidate_id] = candidate.id
        manager_params[:company_id] = 1
        manager_params[:admin_approval] = Hiring.admin_approval.pending
        manager_params[:source] = Hiring.source.candidate
        manager_params[:package_id] = 1
        manager_params[:candidate_salary] = '5000'
        manager_params[:origin] = 1
        manager_params
      end

      it 'should call HiringManagerCreator#creator once with a proper set of params' do
        expect_any_instance_of(Services::Candidates::Hiring::HiringManagerCreator).to receive(:create)
          .once.with(manager_params).and_call_original

        post_candidate_params # gonna invoke the controller and pass hiring_params as argument
      end 

      it 'should create one Hiring, and return a valid http response object with content_type=json and status=200' do
        post_candidate_params # gonna invoke the controller and pass hiring_params as argument

        expect(Hiring.all.count).to be == 1
        expect(response.content_type).to be == 'application/json'
        expect(response.status).to eq 200
      end
    end
```

Now if  _f_ (here `manager_params`) changes not only the test fails but it allow us to precisely know why.

**Comment by paulohenriquepm** [comment]
> Nice issue and cudos for bringing that up. I think it a point worth of discussion with a lot subtleties and I'd try to address some.
> 
> I firmely believe we should adopt a well-defined set of test strategies that apply to _all entrypoint modules_ and eventually cope with particularities as they appear. And I'll try to argue why I think this is better.
> 
> The first strategy is more general and I think it should be part of a separate stylguide for tests. It is the well-known [testing pyramid](https://martinfowler.com/articles/practical-test-pyramid.html), to which I advocate we pay closer attention. This principle entails that we write fewer integration tests than unit ones. By following it, we can safely assume the manager has a set of unit tests that cover the inner business logic. By transitivity that applies to other inner layers as well.
> 
> Another strategy I'm in favor of adoption is the [whitebox testing](https://en.wikipedia.org/wiki/White-box_testing) for integration. Our styleguide implicitly adopts that but it maybe worth making it explict. That means we not only assert responses and interactions with external code (databases, apis) but we also assert how our controller is interacting with the manager. I know this kind of approaching ain't a consensus and I'd like to hear your thoughts on that. To me, it gives us higher confidence that our code is working as expected: image a scenario where we refactor a controller and introduce a bug where new and unexpected arguments are passed to a manager; bug may be shadowed if we don't explicitly assert this inner integration. And even if it surfaces in a database assertion, it is much harder to track it down only by doing that.
> 
> Taking these two strategies into account, there's a way of doing that in RSpec by using [and_call_original](https://relishapp.com/rspec/rspec-mocks/docs/configuring-responses/calling-the-original-implementation): it is like a spy in a real object. That makes easier to write/review/undestand a spec without the need to have two separate scenarios (and additional state control) to do it. But note I'm not saying integration tests are easy to write/maintain; in fact I find them more complicated than unit ones. Good news is: we have fewer :)
> 
> Last but not least, let's assume controllers are responsible for parsing, and to some extend, for transforming the input params into a different object that is passed along to the manager. I.e. it is nothing more than a function _f:A->B_ and therefore we should also make sure we assert _f_, i.e. that for _a in A_, the output _b e B_ is what we hope it is.
> 
> Putting it all together, we could have:
> 
> ```
>     context 'when request params is valid' do
>       let(:hiring_params) do
>         { hiring: {
>           candidate_id: candidate.id,
>           job_id: job.id,
>           candidate_start_date: '2022-02-11 15:54:29 -0300',
>           candidate_salary: 5000,
>           origin: Hiring.origin.package,
>           contract_type: Hiring.contract_type.clt
>         } }
>       end
>       let(:manager_params) do
>         manager_params = ActionController::Parameters.new(hiring_params)
>           .require(:hiring)
>           .permit(:job_id, :candidate_start_date, :candidate_salary, :origin, :contract_type)
>         manager_params[:job_id] = job.id.to_s
>         manager_params[:bid_id] = 1
>         manager_params[:candidate_id] = candidate.id
>         manager_params[:company_id] = 1
>         manager_params[:admin_approval] = Hiring.admin_approval.pending
>         manager_params[:source] = Hiring.source.candidate
>         manager_params[:package_id] = 1
>         manager_params[:candidate_salary] = '5000'
>         manager_params[:origin] = 1
>         manager_params
>       end
> 
>       it 'should call HiringManagerCreator#creator once with a proper set of params' do
>         expect_any_instance_of(Services::Candidates::Hiring::HiringManagerCreator).to receive(:create)
>           .once.with(manager_params).and_call_original
> 
>         post_candidate_params # gonna invoke the controller and pass hiring_params as argument
>       end 
> 
>       it 'should create one Hiring, and return a valid http response object with content_type=json and status=200' do
>         post_candidate_params # gonna invoke the controller and pass hiring_params as argument
> 
>         expect(Hiring.all.count).to be == 1
>         expect(response.content_type).to be == 'application/json'
>         expect(response.status).to eq 200
>       end
>     end
> ```
> 
> Now if _f_ (here `manager_params`) changes not only the test fails but it allow us to precisely know why.

I really really really liked the insights that you brought for us!!! 

I think that with this approach, we are more protected from eventual bugs, like passing an unexpected parameter as you mention, independent of whether we are handling a legacy code or not.

I would like to hear from the others their opinions about it so we can achieve a common idea.

**Comment by Thrashattack** [comment]
Nicely done @joaophellip , i totally agreed with this approach and i belive this is a beautiful beginning for a testing style guide

**Comment by pedro-lb** [comment]
Awesome insights as always, @joaophellip!

I think we are already able to update our styleguide with at least a portion of what we've learned here - test pyramid, whitebox testing and how we should handle the tests for our layers taking all of this into consideration.

Let's open a new PR! 🚀

**Comment by joaophellip** [comment]
Added these consideration to the In Practice Rails section of the PR #30 
I suggest there we use `allow_any_instance_of` instead of `expect_any_instance_of`, but the idea is the same: make sure manager is called with proper arguments.
