### ISSUE TITLE
Less file changes as possible 

### ISSUE THREAD

**Issue by Thrashattack** [GeekHunter-Brasil/hello-world#14]
It's a good approach to do not mess with files not related to you PR. If some adjustment is needed, then another PR should be made with another meaningfull commits. 
More than messing with other files, we need to pay attention to not messing with other `lines`. 
Sometimes we need to deeply understand the reason why a code was implemented on that way, and if you changed a specific line in a not related PR, in a out of context commit, it will make it hard to track this without some complexity. 

In this example i did it wrong, and a lint adjustment was made in a line not related to my PR and now i need to understand the reasons why that line was there and it will need more effort and touchpoints. 
![image](https://user-images.githubusercontent.com/23486776/152216150-5cd660e4-2e8e-48cd-9ebc-1dc53e783e30.png)

**Comment by paulohenriquepm** [comment]
I agree but in some cases, we need to change one single thing on a specific file, and then the linting from rubocop changes the entire file. Is there anything to avoid this, especially when the linting occurs when we save the file?

**Comment by pedro-lb** [comment]
We can simply disable the autoformat for these cases, but they should be really rare (since virtually every file already is or should be formatted).

There's a very good rule of thumb here: PRs should have one and only one objective. A pr can do either of these things, but not both:
- Refactor existing code to format it
- Add a new feature
- Fix a bug
- Improve performance
- Etc

Going by this rule, it's not a "less changes" situation, but more of a "more focus" situation for each PR.

**Comment by joaophellip** [comment]
Great topic. Issues related to linting should disappear when we ready to add rubocop to our CI pipeline. 

I agree with Bini's view that this tends to happen more frequently with PRs not respecting a single responsability principle. 

Also, expanding a bit on PR scope, it's related to the PR size invariably: the smaller the PR the smaller the chance of this happening. Of course there's a sort of 'limit' to how small it can be but nonetheless less is more in this case. Besides. in a small PR the reviewer has a bigger chance of noticing/pointing out changes in files/lines that are clearly out of scope.

Interesting read on the subject: https://essenceofcode.com/2019/10/29/the-art-of-small-pull-requests/
