### ISSUE TITLE
Standardize the use of public assets in the new front-end

### ISSUE THREAD

**Issue by vghellere** [GeekHunter-Brasil/hello-world#20]
In the new front-end we don't have a standard for referencing public assets like images.

In some places we reference using strings like this:
`{ src: '/companies/zup-color-new.png', alt: 'Zup', w: [85], h: [41] },`

And in other places we are using imports:
```
import Carousel1 from '@public/companies/carousel1.webp';

...
panels: [
      {
        title: '📝 01. Cadastre-se',
        panelData: {
          imgSrc: Carousel1,
          imgAlt: 'Homem em reunião com CS da geekhunter',
...

```

## Suggestion
The suggestion is to only make use of the `import` because this way ESLint will validate it and will make the code base more robust.
When referencing it by string there can be inconsistencies in case the Asset doesn't exist.

**Comment by pedro-lb** [comment]
Agreed, we should always use the `import` option that @danisanc prepared to validate files.

@vghellere can you make a PR to update the styleguide?

**Comment by vghellere** [comment]
> Agreed, we should always use the `import` option that @danisanc prepared to validate files.
> 
> @vghellere can you make a PR to update the styleguide?

Yep, sure, I'll do it

**Comment by paulohenriquepm** [comment]
I agree!
