### ISSUE TITLE
Case for constant name

### ISSUE THREAD

**Issue by danisanc** [GeekHunter-Brasil/hello-world#3]
On the front-end we still don't have a pattern for the names of our variables and constants, some are with the default UPPER_CASE (The legacy paths), some are like TitleCase and others like camelCase.

Taking a look at the airbnb styleguide, the default they follow is `camelCase` and makes the use of `UPPER_CASE` optional for some cases, they are:

1. The constant is exported;
3. The developer can trust it (and its nested properties) to **NEVER** change.

For example:

Use camelCase when naming objects, functions and instances:
```typescript
// ❌ Bad
const OBJEcttsssss = {};
const this_is_my_object = {};
function c() {}

// ✅ Good
const thisIsMyObject = {};
function thisIsMyFunction() {}
```

Only use PascalCase when naming constructors or classes:
```typescript
// ❌ Bad
function user(options) {
  this.name = options.name;
}

const bad = new user({
  name: 'nope',
});

// ✅ Good
class User {
  constructor(options) {
    this.name = options.name;
  }
}

const good = new User({
  name: 'yup',
});
```

Use UPPER_CASE optionally when meeting the two points mentioned above:
```typescript
// ❌ Bad
const PRIVATE_VARIABLE = 'Should not be unnecessarily uppercased within a file';

// ❌ Bad
export const THING_TO_BE_CHANGED = 'Should obviously not be uppercased';

// ❌ Bad
export let REASSIGNABLE_VARIABLE = 'So not use let with uppercase variables';


// ✅ Allowed but does not supply semantic value
export const apiKey = 'SOMEKEY';

// ✅ Better in most cases
export const API_KEY = 'SOMEKEY';

// ❌ Bad - unnecessarily uppercases key while adding no semantic value
export const MAPPING = {
  KEY: 'value'
};

// ✅ Good
export const MAPPING = {
  key: 'value'
};
```

In my opinion, the use of `camelCase` in internal variables is clear and is already well-used, but our constants still need a standardization, how do you prefer to declare them? `camelCase` or `UPPER_CASE`?

**Comment by danisanc** [comment]
I start, I think the use of `UPPER_CASE` for constants is ideal for the simplicity of identifying that it is a constant, maybe the code is a little "ugly", but it is more semantic. Variables declared in components and exported to other components must be declared with `camelCase`, as they will not be immutable in most cases.

Examples: 

Use `UPPER_CASE` to declare constants in `/lib/constants`:
```typescript
// ❌ Bad
export const companiesLPHeaderLinks = [
  {
    isFeatured: false,
    isLegacy: true,
    label: 'Para empresas',
    path: legacyPaths.COMPANY_LP,
  },
  {
    isFeatured: false,
    isLegacy: true,
    label: 'Para devs',
    path: paths.CANDIDATE_CREATE_ACCOUNT,
  },
  {
    isFeatured: true,
    isLegacy: true,
    label: 'Login',
    path: legacyPaths.LOGIN,
  },
];

// ✅ Good
export const COMPANIES_LP_HEADERS_LINKS = [
  {
    isFeatured: false,
    isLegacy: true,
    label: 'Para empresas',
    path: legacyPaths.COMPANY_LP,
  },
  {
    isFeatured: false,
    isLegacy: true,
    label: 'Para devs',
    path: paths.CANDIDATE_CREATE_ACCOUNT,
  },
  {
    isFeatured: true,
    isLegacy: true,
    label: 'Login',
    path: legacyPaths.LOGIN,
  },
];
```

Use `camelCase` to declare exported variables inside components:

```typescript
// src/components/molecules/form/field/index.tsx

[...]
import FieldTitle from 'components/atoms/form/fieldTitle';
import getErrorMessage from 'lib/utils/getErrorMessage';

// ❌ Bad
import { VariantsAvailable, variants } from './variants';

// ✅ Good
import { variantsAvailable, variants } from './variants';

export interface FieldProps extends Omit<InputProps, 'h' | 'w'> {
variant?: VariantsAvailable;
label?: string;
[...]
```

**Comment by joaophellip** [comment]
very good proposal in my opinion as it can globally improve our codebase quality by increasing code clarity.

I agree with the usage of camelCase/PascalCase in all contexts described by Dan. And also agree with the proposal to use UPPER_CASE when dealing with _constants_.

Expanding a bit on that, I think UPPER_CASE is great for naming **deeply immutable objects**. Quoting Google JS styleguide:

`Every constant is a @const static property or a module-local const declaration, but not all @const static properties and module-local consts are constants. Before choosing constant case, consider whether the field really feels like a deeply immutable constant. For example, if any of that instance's observable state can change, it is almost certainly not a constant. Merely intending to never mutate the object is generally not enough. `

We usually don't go to great lengths of making sure an UPPER_CASED constant is deeply immutable (ex: using an ImmutableList to headerLinks), but I think that is fine given the complexity of what we do.

**Comment by pedro-lb** [comment]
Agreed.

@danisanc can you update the styleguide?

**Comment by danisanc** [comment]
Added in #11
