### ISSUE TITLE
Test most possible input cases in validators

### ISSUE THREAD

**Issue by renanrcp** [GeekHunter-Brasil/hello-world#4]
On the backend, we don't test all "possible" input cases in our validators.

When a field type is either boolean or enum I propose we exhaustively test all scenarios of inputs for this field.

For example, if we have a field that has a `boolean` type we can test three possible values `nil`, `true` and `false` where `true` and `false` are valid values.

Practical example -> A field named `available` with type `boolean`
```ruby
context 'available' do

  context "when has 'nil' or an empty value" do

    it ':inclusion should be added available' do
      expect(errors.added?(:available, :inclusion)).to be_truthy
    end
  end

  context "when has 'true' value" do
    let(:params) { { available: true } }

    it ':inclusion should not be added available' do
      expect(errors.added?(:available, :inclusion)).to_not be_truthy
    end
  end

  context "when has 'false' value" do
    let(:params) { { available: false } }

    it ':inclusion should not be added available' do
      expect(errors.added?(:available, :inclusion)).to_not be_truthy
    end
  end
end
```
In my opinion, since validators tests are all unit tests we need to test these inputs because this can avoid some problems and headaches.

**Comment by pedro-lb** [comment]
I agree 100% here, validators should cover all edge cases, at least for possible types.

@renanrcp can you update the styleguide?

**Comment by renanrcp** [comment]
PR opened in #13
