### ISSUE TITLE
Comment tables and fields when creating migrations

### ISSUE THREAD

**Issue by renanrcp** [GeekHunter-Brasil/hello-world#5]
Now with Rails 5 we can add comments on tables and their fields.

These comments are important so everyone can understand what information the table holds and what each field represents.

This can be done like this:
```ruby
# frozen_string_literal: true

class ExampleTable < ActiveRecord::Migration[5.0]
  def change
    create_table :example_table, comment: 'The is an example table for this suggestion' do |t|
      t.references :example_reference, index: false, foreign_key: true, comment: 'A reference example'

      t.integer :example_field, comment: 'The is an example field for this table'

      t.timestamps null: false
    end
  end
end

```

**Comment by Thrashattack** [comment]
Good approach. It helps a lot the newcomers . Just let's make sure to keep a Ubiquitous Language,  this way the knowledge about another Geek process can be used to understand the code nuances

**Comment by Thrashattack** [comment]
> Good approach. It helps a lot the newcomers . Just let's make sure to keep a Ubiquitous Language, this way the knowledge about another Geek process can be used to understand the code nuances

I mean... if something is called Customer Ongoing by the CS team, then the table/fields related to it must have the comment mentioning the Customer Onging proccess.

**Comment by renanrcp** [comment]
These comments appear in Metabase too

**Comment by joaophellip** [comment]
Great proposal! 

A securty reminder from PostgreQSL docs:

![image](https://user-images.githubusercontent.com/30455472/151807172-b4d06ed7-7a39-4672-a335-6560765f7cac.png)

**Comment by pedro-lb** [comment]
This is a great idea, we just need to be careful not to make comments that we consider anti-pattern in our code.

For example, this comment is valid since it adds rich info:

```ruby
t.string :phone_number, comment: 'The phone number including country and area code'
```

While this one shouldn't be (we can document this in our styleguide), since it's obvious:

```ruby
t.string :name, comment: 'The name'
```

**Comment by pedro-lb** [comment]
@renanrcp let's update the styleguide =)
